### ISSUE TITLE
数据预处理时遇到问题

### ISSUE THREAD

**Issue by lihuashengmax** [hht1996ok/EA-LSS#18]
作者您好，在两周前您更新了toos/data_converter下的nuscenes_converter.py文件，其中的create_nuscenes_infos函数相比于原来增添了一个can_bus_root_path参数，但是在tools下的create_data.py文件中调用create_nuscenes_infos函数时没有传入can_bus_root_path参数导致数据预处理时遇到报错，请问该如何解决呢？
![1700812882963](https://github.com/hht1996ok/EA-LSS/assets/78634967/8c8aa97e-87b4-46cf-a9aa-795a37c91ca5)

**Comment by CXT-666** [comment]
请问解决了吗

**Comment by lihuashengmax** [comment]
> 请问解决了吗

您好，已经解决了

**Comment by CXT-666** [comment]
> > 请问解决了吗
> 
> 您好，已经解决了
传入路径就可以了，请问有更改ealss, img_backbone和neck 的经验吗，CBSwinTransformer导致显存溢出了

**Comment by lihuashengmax** [comment]
> > > 请问解决了吗
> > 
> > 
> > 您好，已经解决了
> > 传入路径就可以了，请问有更改ealss, img_backbone和neck 的经验吗，CBSwinTransformer导致显存溢出了

您好，有的

**Comment by CXT-666** [comment]
> > > > 请问解决了吗
> > > 
> > > 
> > > 您好，已经解决了
> > > 传入路径就可以了，请问有更改ealss, img_backbone和neck 的经验吗，CBSwinTransformer导致显存溢出了
> 
> 您好，有的

我更改为resnet18和fpn了,后面维度有些对不上,再看看.请问您有实验过ealss的效果吗,有提升吗?

**Comment by lihuashengmax** [comment]
> > > > > 请问解决了吗
> > > > 
> > > > 
> > > > 您好，已经解决了
> > > > 传入路径就可以了，请问有更改ealss, img_backbone和neck 的经验吗，CBSwinTransformer导致显存溢出了
> > 
> > 
> > 您好，有的
> 
> 我更改为resnet18和fpn了,后面维度有些对不上,再看看.请问您有实验过ealss的效果吗,有提升吗?

还没有实验ealss

**Comment by hsingyu-chou** [comment]
@lihuashengmax ,
你好,請問這個有解決了嗎? 怎麼解決的?
我的指令內有包含 --extra-tag nuscenes , 為何會報此錯?

Traceback (most recent call last):
  File "tools/create_data.py", line 236, in <module>
    nuscenes_data_prep(
  File "tools/create_data.py", line 54, in nuscenes_data_prep
    nuscenes_converter.create_nuscenes_infos(
TypeError: create_nuscenes_infos() missing 1 required positional argument: 'info_prefix'
