### ISSUE TITLE
KeyError: 'SwinTransformer is already registered in models'

### ISSUE THREAD

**Issue by liuyuansheng624** [hht1996ok/EA-LSS#21]
Traceback (most recent call last):
File "[train.py](http://train.py/)", line 19, in <module>
from mmdet3d.models import build_detector
File "/home/user6/LYS/EA-LSS-main/mmdet3d/models/init.py", line 1, in <module>
from .backbones import *  # noqa: F401,F403
File "/home/user6/LYS/EA-LSS-main/mmdet3d/models/backbones/init.py", line 2, in <module>
from .cbnet import CBSwinTransformer
File "/home/user6/LYS/EA-LSS-main/mmdet3d/models/backbones/cbnet.py", line 8, in <module>
from .swin_transformer import SwinTransformer
File "/home/user6/LYS/EA-LSS-main/mmdet3d/models/backbones/swin_transformer.py", line 450, in <module>
class SwinTransformer(BaseModule):
File "/home/user6/.conda/envs/ealss/lib/python3.8/site-packages/mmcv/utils/registry.py", line 311, in _register
self._register_module(
File "/home/user6/.conda/envs/ealss/lib/python3.8/site-packages/mmcv/utils/registry.py", line 246, in _register_module
raise KeyError(f'{name} is already registered '
KeyError: 'SwinTransformer is already registered in models'
这是啥情况？

**Comment by xinpuliu** [comment]
请问这个问题您解决了吗？

**Comment by liuyuansheng624** [comment]
加微信交流下13731082126



发自我的iPhone


------------------ Original ------------------
From: xinpuliu ***@***.***&gt;
Date: Mon,Feb 5,2024 3:08 PM
To: hht1996ok/EA-LSS ***@***.***&gt;
Cc: liuys ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [hht1996ok/EA-LSS] KeyError: 'SwinTransformer is alreadyregistered in models' (Issue #21)





 
请问这个问题您解决了吗？

**Comment by liuyuansheng624** [comment]
你好，有关EA-LSS的问题可以一起交流一下么




生生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hht1996ok/EA-LSS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月5日(星期一) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hht1996ok/EA-LSS] KeyError: 'SwinTransformer is already registered in models' (Issue #21)





 
请问这个问题您解决了吗？

**Comment by AleksanderB31** [comment]
Hey, how to resolve this issue?

**Comment by explorer-shy** [comment]
https://github.com/hht1996ok/EA-LSS/blob/193c30141da8625f442d10f0fa29c226694bc3c3/mmdet3d/models/backbones/swin_transformer.py#L449
set ```@BACKBONES.register_module(force=True)``` will solve it.
